all:
	@echo "Instructions for building the library:"
	@echo "\t$ mkdir rabbitmq-c/build"
	@echo "\t$ cd rabbitmq-c/build"
	@echo "\t$ cmake .."
	@echo "\t$ cmake --build ."
	mkdir rabbitmq-c/build && cd rabbitmq-c/build && cmake .. && cmake --build .

clean:
	@echo "Removing rabbitmq-c/build"
	rm -rf rabbitmq-c/build
